@baseUrl = http://localhost:3000/api

#Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "id": "5",
    "name": "Iphone 12"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/5
Content-Type: application/json

{
    "name": "Iphone 11 Pro"
}

###

# @name deleteCategory
DELETE {{baseUrl}}/categories/5
